services:
  provider:
    build: .
    image: yadsendew/ollama_provider:latest
    container_name: ollama_provider
    ports:
      - "3001:3001"
    volumes:
      - ./config.yml:/usr/src/app/config.yml
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  ollama_ui:
    image: yadsendewlung/nextjs-ollama-llm-ui
    ports:
      - "11433:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_OLLAMA_URL: 'http://localhost:11434'
    volumes:
      - ./.env:/app/.env
volumes:
  ollama:
